
[master]
name            = "Lua Configuration"
tags            = ["Tool", "Must be run on server"]
autodescription = true
description     = "README.md"
preview         = "preview.png"
website         = "https://github.com/Laaas/LuaConfig"

[beta]
name            = "Lua Configuration - Beta"
tags            = ["Tool", "Must be run on server"]
autodescription = false
description     = "description.beta.txt"
preview         = "preview.png"
